language: python
python:
  '2.7'
  '3.3'
  '3.4'
  '3.5'
  '3.6'
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - "python setup.py install"
script:
  - "coverage run --source=aacgmv2 setup.py test"
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls
