language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install coveralls
  - "python setup.py install"
  - pip install tox-travis
script: tox
notifications:
  email:
    on_success: never
    on_failure: always
after_success: coveralls
