version: '{branch}-{build}'
build: off
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: check
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: '2.7,codecov'
      TOXPYTHON: C:\python27\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python27.dll
      PYTHON_DEF: python27.def
      LIBPYTHON: libs/libpython27.a
    - TOXENV: '2.7,codecov'
      TOXPYTHON: C:\python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python27.dll
      PYTHON_DEF: python27.def
      LIBPYTHON: libs/libpython27.a
    - TOXENV: '2.7-nocover'
      TOXPYTHON: C:\python27\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python27.dll
      PYTHON_DEF: python27.def
      LIBPYTHON: libs/libpython27.a
    - TOXENV: '2.7-nocover'
      TOXPYTHON: C:\python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python27.dll
      PYTHON_DEF: python27.def
      LIBPYTHON: libs/libpython27.a
    - TOXENV: '3.3,codecov'
      TOXPYTHON: C:\python33\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python33
      PYTHON_VERSION: '3.3'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python33.dll
      PYTHON_DEF: python33.def
      LIBPYTHON: libs/libpython33.a
    - TOXENV: '3.3,codecov'
      TOXPYTHON: C:\python33-x64\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python33-x64
      PYTHON_VERSION: '3.3'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python33.dll
      PYTHON_DEF: python33.def
      LIBPYTHON: libs/libpython33.a
    - TOXENV: '3.3-nocover'
      TOXPYTHON: C:\python33\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python33
      PYTHON_VERSION: '3.3'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python33.dll
      PYTHON_DEF: python33.def
      LIBPYTHON: libs/libpython33.a
    - TOXENV: '3.3-nocover'
      TOXPYTHON: C:\python33-x64\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python33-x64
      PYTHON_VERSION: '3.3'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python33.dll
      PYTHON_DEF: python33.def
      LIBPYTHON: libs/libpython33.a
    - TOXENV: '3.4,codecov'
      TOXPYTHON: C:\python34\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python34.dll
      PYTHON_DEF: python34.def
      LIBPYTHON: libs/libpython34.a
    - TOXENV: '3.4,codecov'
      TOXPYTHON: C:\python34-x64\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python34-x64
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python34.dll
      PYTHON_DEF: python34.def
      LIBPYTHON: libs/libpython34.a
    - TOXENV: '3.4-nocover'
      TOXPYTHON: C:\python34\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python34.dll
      PYTHON_DEF: python34.def
      LIBPYTHON: libs/libpython34.a
    - TOXENV: '3.4-nocover'
      TOXPYTHON: C:\python34-x64\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\python34-x64
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python34.dll
      PYTHON_DEF: python34.def
      LIBPYTHON: libs/libpython34.a
    - TOXENV: '3.5,codecov'
      TOXPYTHON: C:\python35\python.exe
      PYTHON_HOME: C:\python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python35.dll
      PYTHON_DEF: python35.def
      LIBPYTHON: libs/libpython35.a
    - TOXENV: '3.5,codecov'
      TOXPYTHON: C:\python35-x64\python.exe
      PYTHON_HOME: C:\python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python35.dll
      PYTHON_DEF: python35.def
      LIBPYTHON: libs/libpython35.a
    - TOXENV: '3.5-nocover'
      TOXPYTHON: C:\python35\python.exe
      PYTHON_HOME: C:\python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
      PYTHON_DLL: python35.dll
      PYTHON_DEF: python35.def
      LIBPYTHON: libs/libpython35.a
    - TOXENV: '3.5-nocover'
      TOXPYTHON: C:\python35-x64\python.exe
      PYTHON_HOME: C:\python35-x64
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '64'
      PYTHON_DLL: python35.dll
      PYTHON_DEF: python35.def
      LIBPYTHON: libs/libpython35.a
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
  - echo [build]>%userprofile%\pydistutils.cfg
  - echo compiler=mingw32>>%userprofile%\pydistutils.cfg
  - set PATH=C:\MinGW\bin;%PATH%;C:\MinGW\bin
  - echo CONTENTS OF %PYTHON_HOME%
  - dir %PYTHON_HOME%
  - c:\mingw\bin\mingw-get.exe install gendef
  - C:\MinGW\bin\gendef.exe %PYTHON_HOME%\%PYTHON_DLL%
  - C:\MinGW\bin\dlltool.exe --dllname %PYTHON_HOME%\%PYTHON_DLL% --def %PYTHON_HOME%\%PYTHON_DEF% --output-lib %PYTHON_HOME%\%LIBPYTHON%
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'

after_test:
  - IF "%TOXENV:~-8,8%" == "-nocover" %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

